/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "selector",
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        rosePine: {
          base: "#191724",
          surface: "#1f1d2e",
          overlay: "#26233a",
          muted: "#6e6a86",
          subtle: "#908caa",
          text: "#e0def4",
          love: "#eb6f92",
          gold: "#f6c177",
          rose: "#ebbcba",
          pine: "#31748f",
          foam: "#9ccfd8",
          iris: "#c4a7e7",
          highlightLow: "#21202e",
          highlightMed: "#403d52",
          highlightHigh: "#524f67",
        },
        rosePineMoon: {
          base: "#232136",
          surface: "#2a273f",
          overlay: "#393552",
          muted: "#6e6a86",
          subtle: "#908caa",
          text: "#e0def4",
          love: "#eb6f92",
          gold: "#f6c177",
          rose: "#ea9a97",
          pine: "#3e8fb0",
          foam: "#9ccfd8",
          iris: "#c4a7e7",
          highlightLow: "#2a283e",
          highlightMed: "#44415a",
          highlightHigh: "#56526e",
        },
        rosePineDawn: {
          base: "#faf4ed",
          surface: "#fffaf3",
          overlay: "#f2e9e1",
          muted: "#9893a5",
          subtle: "#797593",
          text: "#575279",
          love: "#b4637a",
          gold: "#ea9d34",
          rose: "#d7827e",
          pine: "#286983",
          foam: "#56949f",
          iris: "#907aa9",
          highlightLow: "#f4ede8",
          highlightMed: "#dfdad9",
          highlightHigh: "#cecacd",
        },
        rosewater: "var(--rosewater)",
        flamingo: "var(--flamingo)",
        pink: "var(--pink)",
        mauve: "var(--mauve)",
        red: "var(--red)",
        maroon: "var(--maroon)",
        peach: "var(--peach)",
        yellow: "var(--yellow)",
        green: "var(--green)",
        teal: "var(--teal)",
        sky: "var(--sky)",
        sapphire: "var(--sapphire)",
        blue: "var(--blue)",
        lavender: "var(--lavender)",
        text: "var(--text)",
        subtext1: "hsla(var(--subtext1-hsl)/var(--tw-bg-opacity))",
        subtext0: "hsla(var(--subtext0-hsl)/var(--tw-bg-opacity))",
        overlay2: "hsla(var(--overlay2-hsl)/var(--tw-bg-opacity))",
        overlay1: "hsla(var(--overlay1-hsl)/var(--tw-bg-opacity))",
        overlay0: "hsla(var(--overlay0-hsl)/var(--tw-bg-opacity))",
        surface2: "hsla(var(--surface2-hsl)/var(--tw-bg-opacity))",
        surface1: "hsla(var(--surface1-hsl)/var(--tw-bg-opacity))",
        surface0: "hsla(var(--surface0-hsl)/var(--tw-bg-opacity))",
        base: "hsla(var(--base-hsl)/var(--tw-bg-opacity))",
        mantle: "hsla(var(--mantle-hsl)/var(--tw-bg-opacity))",
        crust: "hsla(var(--crust-hsl)/var(--tw-bg-opacity))",
      },

      fontFamily: {
        chakra: '"Chakra Petch", sans-serif',
      },
    },
    animation: {
      slide: "slide-in 1s linear",
    },
    keyframes: {
      "slide-in": {
        "0%": { translate: "0px -30px", opacity: "0" },
        "100%": { translate: "0px 0px", opacity: "1" },
      },
    },
  },
  plugins: [],
};
